### ISSUE TITLE
Faculty Login

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [coding-Studio-vbit/A.R.M.A#29]
@abhiram2600 can we add a switch option in the login page so that we can switch to faculty login page instead of manually typing the endpoint?
![image](https://user-images.githubusercontent.com/47333094/82570097-c7f3c080-9b9e-11ea-99dc-28d22a1304d1.png)

**Comment by abhiram2600** [comment]
ok i will add a switch to other login page button on both the pages and also on registration page
