### ISSUE TITLE
React Refactoring

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [coding-Studio-vbit/A.R.M.A#36]
- [x] I've created new folders called modules and helpers in the react folder.

- Shift all your modules to your respective module folders. Let the global components like loaders be in **components** folder. 

- Shift all router files and redux files to **helpers** folder.

## IMPORTANT INSTRUCTIONS

1. Create a new branch on your local called *refactoring* and send PRs to *refactoring* branch on Github. *Don't send to master*
2. Name all your filenames in PascalCase.
3. Delete CSS and images folders and add your css files next to component files in module folders.
4. After folder restructuring is done, refactor your `code` and document your files properly.
5. Shift `app.js` to `src` 
6. Before sending a PR, check all paths in your code. Run the app once and make sure everything is running fine.

**Comment by yasaswiraj** [comment]
acknowledged!
