### ISSUE TITLE
Create HODs Dashboard 

### ISSUE THREAD

**Issue by msaichaitanya735** [coding-Studio-vbit/A.R.M.A#4]
Create following components using react
1.Nav Bar
2.Request list Table of Students and Faculty
3.Onclick to review and Button to approve 
4.Profile page

**Comment by Saravanan-Jodavula** [comment]
@msaichaitanya735, please assign the issues to respective members of your team

**Comment by yasaswiraj** [comment]
@Saravanan-Jodavula opened a PR.

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj fix the remaining issues also

**Comment by Saravanan-Jodavula** [comment]
@msaichaitanya735 please remove the tabs option and merge it into navbar
