### ISSUE TITLE
CSS of Labels and Input boxes is inconsistent

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/A.R.M.A#51]
@bsaikiran618 @abhiram2600 @Aaris03Khan  @yasaswiraj  @Vishnu-19  @Anishahaha 

Text labels are invisible because of bad text color.
Input boxes in forms are misaligned
Also mobile view is messy for some components e.g: Profile-ChangePassword etc.

**Comment by Anishahaha** [comment]
solved
