### ISSUE TITLE
Solve the Security Issue.

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [coding-Studio-vbit/A.R.M.A#6]
Acorn's version that is being used in our app is vulnerable to dos apparently. Upgrade the version.
I'm posting the image for reference.
![image](https://user-images.githubusercontent.com/47333094/81271695-1024c600-906a-11ea-9563-f9961b00acc2.png)

**Comment by Saravanan-Jodavula** [comment]
@bsaikiran618 @yasaswiraj @Aaris03Khan look into this issue.

**Comment by bsaikiran618** [comment]
I'm on it
