### ISSUE TITLE
Upload Template allows any type of file to be uploaded

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/A.R.M.A#73]
@abhiram2600  @bsaikiran618  @poojithamutteneni

**Comment by bsaikiran618** [comment]
We must also try to limit the file size

**Comment by bsaikiran618** [comment]
only docx and .odt files must be uploaded

**Comment by abhiram2600** [comment]
what should be the maximum file size?

**Comment by bsaikiran618** [comment]
10 - 15 mb?

**Comment by abhiram2600** [comment]
will there ever be a 10mb docx file?

**Comment by bsaikiran618** [comment]
If they include graphics(images etc.) in the docx then sure.

**Comment by abhiram2600** [comment]
ok

**Comment by abhiram2600** [comment]
Fixed both the issues
