### ISSUE TITLE
Heading is not visible in Forum Letter generation form

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/A.R.M.A#77]
![forumletter](https://user-images.githubusercontent.com/47565414/85410855-3bfdfb80-b585-11ea-92d3-8d5889dc1d70.png)
@poojithamutteneni @ramugoud @KodandaRam66

**Comment by bsaikiran618** [comment]
Also, there is no warning about empty input fields before submission

**Comment by bsaikiran618** [comment]
@poojithamutteneni shall i close this?

**Comment by poojithamutteneni** [comment]
yes close it
