### ISSUE TITLE
Header of generated letter is not properly formed

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/A.R.M.A#78]
![letter](https://user-images.githubusercontent.com/47565414/85411480-0c032800-b586-11ea-88e6-4b1c47343b65.png)
@poojithamutteneni 
@Aaris03Khan 
@ramugoud 
@KodandaRam66

**Comment by Aaris03Khan** [comment]
@bsaikiran618 That is because you are using WPS Office (linux). Once check it in Microsoft word. We will find a way to fix that if possible!

**Comment by bsaikiran618** [comment]
Oh cool

**Comment by poojithamutteneni** [comment]
actually does work properly on word as Aaris said. If you want I'll make the size smaller maybe it might come nicer in yours too. close the issue.
