### ISSUE TITLE
Favicon of arma.codingstudio.club is still react logo

### ISSUE THREAD

**Issue by abhiram2600** [coding-Studio-vbit/A.R.M.A#79]
![2020-06-23 20_13_43-A R M A](https://user-images.githubusercontent.com/59743820/85418379-57b9cf80-b58e-11ea-9a11-558b4e00cd26.png)

**Comment by bsaikiran618** [comment]
Oof this wasn't the case for me

**Comment by abhiram2600** [comment]
yeah if i open on incognito it is showing the correct one
