### ISSUE TITLE
Cancel button doesn't work in forum profile edit for all fields

### ISSUE THREAD

**Issue by bsaikiran618** [coding-Studio-vbit/A.R.M.A#89]
@Anishahaha 
![cancelbutton](https://user-images.githubusercontent.com/47565414/85699041-d0d53600-b6f8-11ea-85d9-ffb60b0fe00a.png)
![cancelbutton1](https://user-images.githubusercontent.com/47565414/85699234-f8c49980-b6f8-11ea-8ceb-3c1ca08c7589.png)
![cancelbutton2](https://user-images.githubusercontent.com/47565414/85699243-fbbf8a00-b6f8-11ea-9310-07c0f8384c02.png)

**Comment by Anishahaha** [comment]
Actually,cancel is supposed to clear the input boxes and for closing it u need to press on cross button @bsaikiran618

**Comment by msaichaitanya735** [comment]
@Anishahaha Instead of "cancel" make it "clear" then.

**Comment by bsaikiran618** [comment]
@Anishahaha

**Comment by Anishahaha** [comment]
fixed it.
