### ISSUE TITLE
Hierarchial request approval.

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [coding-Studio-vbit/A.R.M.A#95]
Use this thread for discussing and implementing Hierarchial Request Approval.

**Comment by Saravanan-Jodavula** [comment]
@akshayrajp The approach I have in mind is, we'll add multiple columns in the request table for multiple requestees. Right now, when someone approves a request. The approval column is directly being edited. We'll change that to editing his respective column. Each requestee will have his respective approval column. So when all of them approve their respective columns, change the whole status thing to `APPROVED` using PostgreSQL functions. Tag me here and let me know whenever you make any progress.

**Comment by Saravanan-Jodavula** [comment]
@akshayrajp one more thing. It'd be great if we can also do it in such a way that requestee 2 can see his request only when requestee 1 approved it.

**Comment by akshayrajp** [comment]
> @akshayrajp one more thing. It'd be great if we can also do it in such a way that requestee 2 can see his request only when requestee 1 approved it.

So I'm assuming that requestees are sorted according to their hierarchy?

**Comment by Saravanan-Jodavula** [comment]
> > @akshayrajp one more thing. It'd be great if we can also do it in such a way that requestee 2 can see his request only when requestee 1 approved it.
> 
> So I'm assuming that requestees are sorted according to their hierarchy?

@akshayrajp yes, I mean there will be 3 or 4 requestees who are hierarchial in order. people who are assigned these roles will be dynamic.
